import { CartProvider } from "./cart/CartContext";
import Header from "./header/page";
import Script from 'next/script';

<Script
  src="your-script.js"
  strategy="beforeInteractive" // or "afterInteractive" depending on when you want it to load
/>



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}) {
  return (  
<html lang="en" >
        <head>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossOrigin="anonymous"/>
          <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossOrigin="anonymous"></Script>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"></link>
        </head>
        <CartProvider>
          <body>
            <header>  
              <Header/>
            </header>
            <hr></hr>
            <section className="container">
                <main>
                  {children}
                </main>
            </section>
          </body>
        </CartProvider>
</html>
  );
}
